openapi: 3.1.0
info:
  title: Pricing API
  version: 1.0.0
  description: |
    The Pricing API allows developers to pull pricing data for self-storage facilities and geographies.
    Time rollups are defined via the timeframe object; geography rollups are accessed through market rollup endpoints.
    Features are combined using **AND** logic; to achieve **OR** behavior, send separate requests.

servers:
  - url: https://api.example.com
    description: Production server

tags:
  - name: Facility Pricing
  - name: Market Pricing

components:
  schemas:
    RollupEnum:
      type: string
      enum: [daily, weekly, monthly, quarterly, yearly]

    Timeframe:
      type: object
      required: [type, value, rollup]
      properties:
        type:
          type: string
          enum: [date, week, month, quarter, year]
        value:
          type: string
          description: Supports single or range values (e.g. "2025-09" or "2025-09/2025-10")
        rollup:
          $ref: '#/components/schemas/RollupEnum'

    Facility:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string

    Geography:
      type: object
      properties:
        address:
          type: string
        distance:
          type: number
        units:
          type: string
          enum: [miles, kilometers]
        type:
          type: string
          enum: [us_address_radius]

    PricingEntry:
      type: object
      properties:
        type:
          type: string
          enum: [web, instore]
        price:
          type: number
          nullable: true
        currency:
          type: string
          example: USD
        last_updated:
          type: string
          format: date-time
          nullable: true

    AggregatedPricingEntry:
      type: object
      properties:
        date:
          type: string
        type:
          type: string
          enum: [web, instore]
        high:
          type: number
          nullable: true
        low:
          type: number
          nullable: true
        avg:
          type: number
          nullable: true
        currency:
          type: string
          example: USD

    UnitPricing:
      type: object
      properties:
        unit_size:
          type: string
        status:
          type: string
          nullable: true
        promo_text:
          type: string
          nullable: true
        features:
          type: array
          items:
            type: string
        source_url:
          type: string
          format: uri
          nullable: true
        pricing:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/PricingEntry'
              - $ref: '#/components/schemas/AggregatedPricingEntry'

    FacilityResponse:
      type: object
      properties:
        facility:
          $ref: '#/components/schemas/Facility'
        units:
          type: array
          items:
            $ref: '#/components/schemas/UnitPricing'

    MarketResponse:
      type: array
      items:
        $ref: '#/components/schemas/FacilityResponse'

    MarketRollupResponse:
      type: array
      items:
        type: object
        properties:
          units:
            type: array
            items:
              $ref: '#/components/schemas/UnitPricing'

  requestBodies:
    FacilityBase:
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [address, unit_sizes, features, pricing_type]
            properties:
              address:
                type: string
              unit_sizes:
                type: array
                items: { type: string }
              features:
                type: array
                items: { type: string }
              pricing_type:
                type: array
                items: { type: string, enum: [web, instore] }

    FacilityWithTimeframe:
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/requestBodies/FacilityBase/content/application~1json/schema'
              - type: object
                properties:
                  timeframe:
                    $ref: '#/components/schemas/Timeframe'

    MarketBase:
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [geography, unit_sizes, features, pricing_type]
            properties:
              geography:
                $ref: '#/components/schemas/Geography'
              unit_sizes:
                type: array
                items: { type: string }
              features:
                type: array
                items: { type: string }
              pricing_type:
                type: array
                items: { type: string, enum: [web, instore] }

    MarketWithTimeframe:
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/requestBodies/MarketBase/content/application~1json/schema'
              - type: object
                properties:
                  timeframe:
                    $ref: '#/components/schemas/Timeframe'

paths:
  /facility/pricing/current:
    post:
      tags: [Facility Pricing]
      summary: Get current facility pricing
      requestBody:
        $ref: '#/components/requestBodies/FacilityBase'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityResponse'

  /facility/pricing/historical:
    post:
      tags: [Facility Pricing]
      summary: Get historical facility pricing
      requestBody:
        $ref: '#/components/requestBodies/FacilityWithTimeframe'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityResponse'

  /market/pricing/current:
    post:
      tags: [Market Pricing]
      summary: Get current pricing for facilities within a market
      requestBody:
        $ref: '#/components/requestBodies/MarketBase'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketResponse'

  /market/pricing/current/rollup:
    post:
      tags: [Market Pricing]
      summary: Get current market-level rolled-up pricing
      requestBody:
        $ref: '#/components/requestBodies/MarketBase'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketRollupResponse'

  /market/pricing/historical:
    post:
      tags: [Market Pricing]
      summary: Get historical pricing for facilities within a market
      requestBody:
        $ref: '#/components/requestBodies/MarketWithTimeframe'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketResponse'

  /market/pricing/historical/rollup:
    post:
      tags: [Market Pricing]
      summary: Get historical rolled-up pricing for a market
      requestBody:
        $ref: '#/components/requestBodies/MarketWithTimeframe'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketRollupResponse'
